### ISSUE TITLE
New Cremator NPC Features

### ISSUE THREAD

**Issue by epicplayer40** [epicplayer40/manwich-oddyssey-src#27]
- Can aim immolators properly without shooting at off-angles, either by cheating or doing MAFFS.
- Can resist being ignited by fire and their own damage.
- Can use special attack 1 (constant directed beam for a few seconds)
- Can use special attack 2 (constant wild sweep of beam for a few seconds)
- Can use anim events to enable/disable hose during animations.
- Uses breathing loop sound that changes to a panicked version when on low health.
- Supports Hammer inputs for force enabling/disabling hose usage.

**Comment by LychyLychy** [comment]
All has been done but the the first target, @epicplayer40 needs to fix the aim matrices..

**Comment by epicplayer40** [comment]
Cremators should detect when they're not hitting anything with the immolator beam in their current pos, and then reposition.
Cremators should aim slowly and interpolate their aim, rather than snap to instantly flame someone.
Cremators have an invisible "fuel" number that decreases as they immolate and slowly recharges when not immolating, if the fuel runs out then the cremator has to play their unjamming animation to refill the fuel back to full. Max fuel can be controlled by a cvar.
COND_CREMATOR_OUT_OF_FUEL

**Comment by LychyLychy** [comment]
Still to do "Cremators should detect when they're not hitting anything with the immolator beam in their current pos, and then reposition.
"
