### ISSUE TITLE
npc_gascit cannot roll due to missing schedules.

### ISSUE THREAD

**Issue by epicplayer40** [epicplayer40/manwich-oddyssey-src#3]
The gasmask citizen NPC's roll1 and roll2 schedules do not function, so he just stands still when under attack.

**Comment by epicplayer40** [comment]
Update, this only seems to happens sometimes (?). I'm not too sure how consistant this is.

**Comment by RoyaleNoir** [comment]
I'm not the most well versed in AI schedules but there doesn't seem to be anything that would cause this

**Comment by epicplayer40** [comment]
AI is gonna get overhauled
